### PR TITLE
Add integration to rebar3_format

### PR DESCRIPTION
**Pull request by elbrujohalcon**
…as requested by @awalterschulze in AdRoll/rebar3_format#177.

BTW… I ❤️   the new stringified API… Thank you!

### CODE REVIEW

**Comment by awalterschulze** [comment]
Awesome.

Are you saying that this new rebar compatible API https://github.com/WhatsApp/erlfmt/blob/master/doc/RebarUsage.md now solves https://github.com/WhatsApp/erlfmt/issues/113 ?

**Review by awalterschulze — APPROVED** [review]

**Comment by elbrujohalcon** [comment]
No… #113 is pretty much still active, I still need to translate `require_pragma` and `ignore_pragma` into `{pragma, require | ignore | …}`.

**Comment by elbrujohalcon** [comment]
This is what I want to remove: https://github.com/AdRoll/rebar3_format/blob/a6af41ac30d52bf7c5b869780973d705a465c77d/src/formatters/erlfmt_formatter.erl#L23-L41

**Comment by awalterschulze** [comment]
I was optimistically hoping I got lucky.
I reply more in the issue

**Pull request merged**
