### PR TITLE
Fix formatter comparison summary typo

### PR DESCRIPTION
**Pull request by dtip**

### CODE REVIEW

**Comment by awalterschulze** [comment]
Could you provide some more context?

**Comment by dtip** [comment]
Sure. The comparison analysis shows steamroller does preserve some representation but that didn't make its way into the summary tables.

**Comment by awalterschulze** [comment]
Ah yes good catch.

Do you want to sign the CLA or should I fix it?

**Comment by awalterschulze** [comment]
@dtip hello?

**Comment by dtip** [comment]
Sorry, I missed the notification you'd replied! Please go ahead and fix it

**Comment by awalterschulze** [comment]
Cool done.
Thanks again for bringing this to our attention.

**Pull request closed without merging**
